id_item,aparelho_eletronico,quantidade,preco,cidade,cliente
PRD-1072,ASUS,71.0,7887.59,Espigão d'Oeste,Igor Ferreira
PRD-1073,Nokia,137.0,3515.33,Porto Velho,Daniel Almeida
PRD-1074,Realme,45.0,5560.74,Vilhena,Carlos Santos
PRD-1075,Nokia,88.0,6773.97,Jaru,Patricia Gomes
PRD-1076,Samsung,98.0,8175.84,Cacoal,Igor Silva
PRD-1077,Nokia,0.0,5063.25,Espigão d'Oeste,Vanessa Costa
PRD-1078,motorola,93.0,4336.54,Buritis,Lucas Gomes
PRD-1079,ASUS,31.0,6701.88,Vilhena,Thiago Rodrigues
PRD-1080,Nokia,83.0,4099.58,Vilhena,Vanessa Oliveira
PRD-1081,Motorola,107.0,6252.32,Rolim de Moura,Fernanda Gomes
PRD-1082,Realme,103.0,5292.99,Porto Velho,Juliana Rodrigues
PRD-1083,Motorola,110.0,7243.12,Pimenta Bueno,Lucas Pereira
PRD-1084,LG,113.0,6340.04,Ouro Preto do Oeste,Sofia Martins
PRD-1085,Xiaomi,21.0,,Buritis,Camila Ferreira
PRD-1086,Samsung,60.0,6316.82,Cacoal,Gabriel Oliveira
PRD-1087,Apple,11.0,2807.61,Guajará-Mirim,Camila Carvalho
PRD-1088,Samsung,116.0,4198.32,Buritis,Willian Souza
PRD-1089,Nokia,126.0,4077.05,Ariquemes,Ana Almeida
PRD-1090,Samsung,108.0,2594.4,Espigão d'Oeste,Thiago Pereira
PRD-1091,Apple,142.0,2843.33,Alta Floresta d'Oeste,Daniel Pereira
PRD-1092,Xiaomi,118.0,6274.04,Ouro Preto do Oeste,camila ferreira
PRD-1093,LG,129.0,4299.17,São Miguel do Guaporé,Vanessa Pereira
PRD-1094,Xiaomi,121.0,4490.47,Espigão d'Oeste,Helena Carvalho
PRD-1095,Realme,133.0,4773.6,Cacoal,Igor Pereira
PRD-1096,Samsung,73.0,2722.75,Jaru,Lucas Almeida
PRD-1097,Samsung,35.0,2036.71,Rolim de Moura,Eduardo Ribeiro
PRD-1098,Motorola,16.0,4201.82,Jaru,Vanessa Pereira
PRD-1099,Nokia,15.0,2495.94,Rolim de Moura,Natan Almeida
PRD-1100,Apple,147.0,3919.02,Porto Velho,Mariana Rodrigues
