id_item	aparelho_eletronico	preco	quantidade	cliente	cidade	estado
PRD-1072	Asus	7887.59	71	Igor Ferreira	Espigão d'Oeste	RO
PRD-1073	Nokia	3515.33	137	Daniel Almeida	Porto Velho	RO
PRD-1074	Realme	5560.74	45	Carlos Santos	Vilhena	RO
PRD-1075	Nokia	6773.97	88	Patricia Gomes	Jaru	RO
PRD-1076	Samsung	8175.84	98	Igor Silva	Cacoal	RO
PRD-1077	Nokia	5063.25	0	Vanessa Costa	Espigão d'Oeste	RO
PRD-1078	Motorola	4336.54	93	Lucas Gomes	Buritis	RO
PRD-1079	Asus	6701.88	31	Thiago Rodrigues	Vilhena	RO
PRD-1080	Nokia	4099.58	83	Vanessa Oliveira	Vilhena	RO
PRD-1081	Motorola	6252.32	107	Fernanda Gomes	Rolim de Moura	RO
PRD-1082	Realme	5292.99	103	Juliana Rodrigues	Porto Velho	RO
PRD-1083	Motorola	7243.12	110	Lucas Pereira	Pimenta Bueno	RO
PRD-1084	Lg	6340.04	113	Sofia Martins	Ouro Preto do Oeste	RO
PRD-1085	Xiaomi		21	Camila Ferreira	Buritis	RO
PRD-1086	Samsung	6316.82	60	Gabriel Oliveira	Cacoal	RO
PRD-1087	Apple	2807.61	11	Camila Carvalho	Guajará-Mirim	RO
PRD-1088	Samsung	4198.32	116	Willian Souza	Buritis	RO
PRD-1089	Nokia	4077.05	126	Ana Almeida	Ariquemes	RO
PRD-1090	Samsung	2594.4	108	Thiago Pereira	Espigão d'Oeste	RO
PRD-1091	Apple	2843.33	142	Daniel Pereira	Alta Floresta d'Oeste	RO
PRD-1092	Xiaomi	6274.04	118	Camila Ferreira	Ouro Preto do Oeste	RO
PRD-1093	Lg	4299.17	129	Vanessa Pereira	São Miguel do Guaporé	RO
PRD-1094	Xiaomi	4490.47	121	Helena Carvalho	Espigão d'Oeste	RO
PRD-1095	Realme	4773.6	133	Igor Pereira	Cacoal	RO
PRD-1096	Samsung	2722.75	73	Lucas Almeida	Jaru	RO
PRD-1097	Samsung	2036.71	35	Eduardo Ribeiro	Rolim de Moura	RO
PRD-1098	Motorola	4201.82	16	Vanessa Pereira	Jaru	RO
PRD-1099	Nokia	2495.94	15	Natan Almeida	Rolim de Moura	RO
PRD-1100	Apple	3919.02	147	Mariana Rodrigues	Porto Velho	RO
